import React, { Component } from 'react';
import img from '../../../images/Ashihara_kaikan_logo.jpg'

class History extends Component {

    constructor(props) {
        super(props);
        this.state = {
            readMore: false
        }
    }

    readMore = () => {
        this.setState({
            readMore: !this.state.readMore
        })
        if (this.state.readMore) {
            window.location.href = "#history"
        }

    }

    render() {
        return (
            <section id="history">
                <br /><br /><br /><br />

                <div className="card-group">

                    <div data-aos="fade-up" className="card shadow p-3 mb-5 rounded bg-base" >
                        <h3 className="card-header text-center text-white">History of International ASHIHARA KAIKAN KARATE.</h3>
                        <img className="card-img-top" src={require('../../../images/homepage/History of Ashihara Karate International.jpg')} alt="Card  cap" />
                    </div>

                    <div data-aos="fade-up" className="card shadow p-3 mb-5 bg-white rounded">

                        <div className="card-body">

                            <div className="card-text">
                                <p style={{ marginTop: '0in', marginRight: '0in', marginBottom: '10.0pt', marginLeft: '0in', lineHeight: '115%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'center' }}><strong><span style={{ fontSize: '16px', lineHeight: '115%', fontFamily: '"Times New Roman",serif' }}>SENDAI KANCHO HIDEYUKI ASHIHARA</span></strong></p>
                                <p style={{ marginTop: '0in', marginRight: '0in', marginBottom: '10.0pt', marginLeft: '0in', lineHeight: '115%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify' }}><span style={{ fontSize: '16px', lineHeight: '115%', fontFamily: '"Times New Roman",serif' }}>The late Kancho Hideyuki Ashihara trained in Kendo from the fourth year to ninth year in school. After he left school at the age of 16 went to Tokyo to find a job but was interested in doing some exercises. He was interested in learning Karate and one day saw a poster about Karate classes. This led him to Oyama Dojo in Ikebukuro. He joined then and there and started to learn Karate every day. He at the first grading test after nine months was awarded the green belt and progressed soon to brown belt and then after three and a half years was awarded the Sho Dan grade at the age of 19. After two more years in 1966 he was made an instructor of Oyama Dojo which soon changed the name to Kokusai Karate Do Kyokushin Kai Kan and has just built a new dojo near the Ikebukuro station.&nbsp;</span></p>
                                <p style={{ marginTop: '0in', marginRight: '0in', marginBottom: '10.0pt', marginLeft: '0in', lineHeight: '115%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify' }}><span style={{ fontSize: '16px', lineHeight: '115%', fontFamily: '"Times New Roman",serif' }}>Young instructor Ashihara was sent to shikoku to teach karate there. He was to go to Brazil as an instructor, but he decided to spread the art in Nomura. As the town was too small to spread karate, he decided to move to Uwa-jima. However as this was situated too far to the south, he decided to find a dojo to train in Yawathahama. He started training his students at the Police training facility. Initially he had 55 members for training. After an encounter at the dojo with a student weighing 100Kg and knocking him down with a right Mawaeshi geri to his left chin, he worked out a way of handling heavier opponents and also the way in handling a few attackers at the same time in a brawl. While they trained in the dojo, Shihan Ashihara began to develop his own technique to full fill the above requirement easily, the foundation of SABAKI which later became his life work. This was based on three main points, the four lines, maai and positioning. He went deep into this principle and came up with the Sabaki method.</span></p>
                                {
                                    this.state.readMore && (
                                        <>
                                            <p style={{ marginTop: '0in', marginRight: '0in', marginBottom: '10.0pt', marginLeft: '0in', lineHeight: '115%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify' }}><span style={{ fontSize: '16px', lineHeight: '115%', fontFamily: '"Times New Roman",serif' }}>As they did not have a permanent place of their own for training, with the help of well-wishers and contributions from students’ parents managed to build a two-story dojo in three years. This dojo is being taken care of by Shihan Noriyoshi Nakamoto. Shihan Ashihara moved to Matsuyama and prepared the groundwork to build a new dojo in Matsuyama City on the advice of Master Shohei Mori. Shihan Ashihara and his newly married wife moved to a rented out flat. Shihan Ashihara put up posters to announce that a Karate Instructor has arrived in Matsuyama City. Initially he had only ten members. At the same time, he received an invitation to train the young lions at the Police training school. The Sabaki method matured and got established at this police academy. More and more people joined from the police, Ehime university, Matsuyama university, Medical College and other institutions. The popularity of his teaching and the new style spread so far and wide that the numbers swelled beyond three hundred, He was invited to train in other dojo in the mainland going even beyond Hiroshima.&nbsp;</span></p>
                                            <p style={{ marginTop: '0in', marginRight: '0in', marginBottom: '10.0pt', marginLeft: '0in', lineHeight: '115%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify' }}><span style={{ fontSize: '16px', lineHeight: '115%', fontFamily: '"Times New Roman",serif' }}>Shihan Ashihara was pressurized by his pupils to build a more spacious training hall in Matsuyama City. Master Shohei Mori too helped Shihan Ashihara in this project. The construction of the dojo commenced in March 1978 and the opening took place in 1979.</span></p>
                                            <p style={{ marginTop: '0in', marginRight: '0in', marginBottom: '10.0pt', marginLeft: '0in', lineHeight: '115%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify' }}><span style={{ fontSize: '16px', lineHeight: '115%', fontFamily: '"Times New Roman",serif' }}>When Shihan Ashihara attended the conference of the heads of all the branches held in Tokyo in March 1978, he felt that the atmosphere was not that welcoming. The other branch chiefs complained of their students attending training classes conducted by Ashihara Shihan. Kancho Oyama saw this investment as a waste of money. He demanded more money to be sent to the headquarters as membership fees. Shihan Ashihara at the end of the conference made an announcement that he would resign from the organization within twelve months. However, after a few months Shihan Ashihara received a letter informing him that he is permanently expelled from the organization. &nbsp;</span></p>
                                            <p style={{ marginTop: '0in', marginRight: '0in', marginBottom: '10.0pt', marginLeft: '0in', lineHeight: '115%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify' }}><span style={{ fontSize: '16px', lineHeight: '115%', fontFamily: '"Times New Roman",serif' }}>Kancho Ashihara, pondered what he should do. He could not let down the many students he had which numbered over three hundred and fifty. He decided to form his own organization. &nbsp;He named it as, Shin Kokusai Karate Do Renmei Ashihara Kai Kan. Soon, there were many dojo established, with some dojo as far as Ibaraki in the main island. Before long quite a few branches were established outside Japan and this organization in Sri Lanka is the second one to be established outside Japan, the branch in Australia being the first.&nbsp;</span></p>
                                            <p style={{ marginTop: '0in', marginRight: '0in', marginBottom: '10.0pt', marginLeft: '0in', lineHeight: '115%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify' }}><span style={{ fontSize: '16px', lineHeight: '115%', fontFamily: '"Times New Roman",serif' }}>Kancho Ashihara could not continue the good work he started as he succumbed to a rare kind of disease called ALS a disease which effects the nervous system on 24th of April 1995.&nbsp;</span></p>
                                            <p style={{ marginTop: '0in', marginRight: '0in', marginBottom: '10.0pt', marginLeft: '0in', lineHeight: '115%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify' }}><span style={{ fontSize: '16px', lineHeight: '115%', fontFamily: '"Times New Roman",serif' }}>&nbsp;</span></p>
                                            <p style={{ marginTop: '0in', marginRight: '0in', marginBottom: '10.0pt', marginLeft: '0in', lineHeight: '115%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'center' }}><strong><span style={{ fontSize: '16px', lineHeight: '115%', fontFamily: '"Times New Roman",serif' }}>THE FIRST BRANCH CHIEF LATE SENSEI D. A. WEILGAMA</span></strong></p>
                                            <p style={{ marginTop: '0in', marginRight: '0in', marginBottom: '10.0pt', marginLeft: '0in', lineHeight: '115%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify' }}><span style={{ fontSize: '16px', lineHeight: '115%', fontFamily: '"Times New Roman",serif' }}>To introduce late Sensei D. A. Weilgama as a Karate legend is no exaggeration, as he began the study of this martial art way back in 1960. Over the years, he trained under four instructors one American, one German and two Japanese. After further training, he sends in his credentials to Master Masutatsu Oyama and after careful study of his lengthy movie of his techniques and other aspects of Karate, he was awarded the Black Belt of Sho Dan grade. After further training he was appointed as the Branch Chief for Kyokushin Karate in Ceylon in early 1967. He was the first person to receive a black belt and authorization to open a branch in Sri Lanka. form a recognized Karate organization in Japan. This Karate style was a strong real fight (Honto Kumite) Karate style and spread very fast throughout the country. In early 1970's Sensei Weilgama was invited to train the Sri Lanka Army, Navy, and some special divisions of the Police.</span></p>
                                            <p style={{ marginTop: '0in', marginRight: '0in', marginBottom: '10.0pt', marginLeft: '0in', lineHeight: '115%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify' }}><span style={{ fontSize: '16px', lineHeight: '115%', fontFamily: '"Times New Roman",serif' }}>In late 1963, the first ever Karate training hall was established as Korenkai Karate Dojo which had a quite number of students. As Karate became popular more dojo had to be established in most parts of the island to quench the thirst of young enthusiasts. In 1975 Sensei Weilgama represented Sri Sri Lanka with a team of four members at the First World Open Karate Tournament in Japan. This was the first ever official representation of Sri Lankan Karate in a world event. This was followed by another sojourn to India in 1978 to participate in the South Asia Karate Tournament. His team compriced of five 5 members for this event. Sensei Weilgama served as a Referee and Judge at this tournament. Sensei Weilgama once again represented Sri Lanka at the Second World Open Karate Tournament with a team of two members held in Japan in 1979. He also had the honour of acting as a judge at this event. Sensei Weilgama was later graded to the rank of Ni Dan by Shihan Len Barnes, the branch chief of South Africa.&nbsp;</span></p>
                                            <p style={{ marginTop: '0in', marginRight: '0in', marginBottom: '10.0pt', marginLeft: '0in', lineHeight: '115%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify' }}><span style={{ fontSize: '16px', lineHeight: '115%', fontFamily: '"Times New Roman",serif' }}>Later, Sensei Weilgama resigned from the International Karate Organization Kyokushin Kai in late 1981. In mid of 1982, he was invited by Kancho Hideyuki Ashihara of New International Karate Organization Ashihara Kai Kan of Ehime-Ken, Japan to shoulder the responsibility as a Shibucho of Sri Lanka. Sensei Weilgama readily accepted the offer. A few weeks later he was also appointed as the regional director for South East Asia. This Karate style (Ashihara Karate) developed by Kancho Hideyuki Ashihara became very popular as this is a very rational Karate style when compared to all other karate styles to be seen today.</span></p>
                                            <p style={{ marginTop: '0in', marginRight: '0in', marginBottom: '10.0pt', marginLeft: '0in', lineHeight: '115%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify' }}><span style={{ fontSize: '16px', lineHeight: '115%', fontFamily: '"Times New Roman",serif' }}>Sensei Weilgama could not continue for very long as he succumbed to an injury sustained in a motor accident and passed away on 30th November 1984. Late Sensei D. A. Weilgama was a cut above all in the Karate fraternity and was a charismatic figure and carried himself well in the society. &nbsp;</span></p>
                                            <p style={{ marginTop: '0in', marginRight: '0in', marginBottom: '10.0pt', marginLeft: '0in', lineHeight: '115%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify' }}><span style={{ fontSize: '16px', lineHeight: '115%', fontFamily: '"Times New Roman",serif' }}>&nbsp;</span></p>
                                            <p style={{ marginTop: '0in', marginRight: '0in', marginBottom: '10.0pt', marginLeft: '0in', lineHeight: '115%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'center' }}><strong><span style={{ fontSize: '16px', lineHeight: '115%', fontFamily: '"Times New Roman",serif' }}>THE BRANCH CHIEF SENSEI D.C.M. KARUNATILLEKE</span></strong></p>
                                            <p style={{ marginTop: '0in', marginRight: '0in', marginBottom: '10.0pt', marginLeft: '0in', lineHeight: '115%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify' }}><span style={{ fontSize: '16px', lineHeight: '115%', fontFamily: '"Times New Roman",serif' }}>The present branch chief of the Sri Lanka Karate Kai Kan - Ashihara Karate is Sensei, Dayan C. M. Karunatilleke. He became interested in martial arts having seen an exhibition of Judo at his own school in 1960. He had to wait for an opportune moment to join a club and start a formal class under a good instructor. He joined the Dehiwala Y. M. C. A. &nbsp;in 1966 December and started training in Judo under the famous Judo instructor Mr. Malcolm Atapattu the National Coach of Ceylon.</span></p>
                                            <p style={{ marginTop: '0in', marginRight: '0in', marginBottom: '10.0pt', marginLeft: '0in', lineHeight: '115%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify' }}><span style={{ fontSize: '16px', lineHeight: '115%', fontFamily: '"Times New Roman",serif' }}>In the latter part of 1967, the Dehiwala Y.M.C.A. staged a Judo exhibition to collect funds to build a new gymnasium. At this exhibition two of the seniors in the class demonstrated some breaking techniques with bare knuckles and fingertips. Again, young Karunatilleke was interested to learn this new art. When inquired the seniors reluctantly divulged the name of this art as Karate, and was introduced to Sensei D. A.Weilgama, the branch chief and chief instructor of Ceylon Karate-Do Kyokushin Kai. In the same year of 1974, he received his brown belt in both Judo and Karate.</span></p>
                                            <p style={{ marginTop: '0in', marginRight: '0in', marginBottom: '10.0pt', marginLeft: '0in', lineHeight: '115%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify' }}><span style={{ fontSize: '16px', lineHeight: '115%', fontFamily: '"Times New Roman",serif' }}>In 1975 Sempai Karunatilleke with Sensei Weilgama and three others represented Sri Lanka at the First World Open Karate Tournament held in Tokyo, Japan. He once again represented Sri Lanka, at the Second World Open Karate Tournament held at the Budokan Hall in Tokyo in 1979. In 1978, Sensei Karunatilleke acted as a judge in the All India Kyokushin Karate Tournament held in Calcutta. In the year of 1980, he was awarded the Ni Dan black belt by Shihan Len Barnes, the Kyokushin branch chief of South Africa.</span></p>
                                            <p style={{ marginTop: '0in', marginRight: '0in', marginBottom: '10.0pt', marginLeft: '0in', lineHeight: '115%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify' }}><span style={{ fontSize: '16px', lineHeight: '115%', fontFamily: '"Times New Roman",serif' }}>The untimely demise of Branch Chief and Chief Instructor Sensei Weilgama, Kancho Hideyuki Ashihara appointed Sensei D. C. M. Karunatilleke as the new Branch Chief of Sri Lanka in 1986. &nbsp;In the same year, represented Sri Lanka as the coach of a three-member team that took part in the South Asian Ashihara Karate tournament held in 1986 in Calcutta. After the event, the entire team had an intensive training for three days in Ashihara Karate, with Sensei Shumei Tamaki under the watchful eye of Kancho, Hideyuki Ashihara. Four times at various occasions, Sensei Karunatilleke has been to NIKO Ashihara Kai Kan, So Honbu in Matsuyama City, Japan for further trainings.</span></p>
                                            <p style={{ marginTop: '0in', marginRight: '0in', marginBottom: '10.0pt', marginLeft: '0in', lineHeight: '115%', fontSize: '15px', fontFamily: '"Calibri",sans-serif', textAlign: 'justify' }}><span style={{ fontSize: '16px', lineHeight: '115%', fontFamily: '"Times New Roman",serif' }}>In addition to his interest in Karate and Judo, he is an adept in AikiKai Aikido and Kashimasen Ryu Kenjutsu.</span></p>

                                        </>
                                    )
                                }
                                <button onClick={this.readMore} className="btn btn-primary">{this.state.readMore ? 'Read Less' : 'Read More'}</button>
                            </div>
                        </div>

                    </div>
                </div>


            </section>
        );
    }
}

export default History;